[package]
name = "TaigaBot2"
version = "0.1.0"
authors = ["duck <duckisanidiot@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.7"
serde = "1.0.100"
serde_json = "1.0.40"
reqwest = "0.9.20"
